"use client";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Calculator, CheckCircle2, Download, Loader2, ShieldCheck } from "lucide-react";
import { useI18n } from "@/lib/i18n";

type Preview = { product: { id: string; name: string }; quantity: number; currency: string; unitPrice: number; subtotal: number; discountRate: number; discountAmount: number; total: number; validUntil: string };
type Saved = { quoteNumber: string; total: number; currency: string; validUntil: string; pdfUrl: string };

export default function QuoteBuilder() {
  const params = useSearchParams(); const { lang, currency } = useI18n(); const zh = lang === "zh"; const t = (en: string, cn: string) => zh ? cn : en;
  const [productId, setProductId] = useState(params.get("product") || ""); const [quantity, setQuantity] = useState(1); const [selectedCurrency, setSelectedCurrency] = useState(currency);
  const [preview, setPreview] = useState<Preview | null>(null); const [saved, setSaved] = useState<Saved | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => setSelectedCurrency(currency), [currency]);

  async function calculate() { if (!productId.trim()) return; setLoading(true); setError(""); setSaved(null); try { const query = new URLSearchParams({ product: productId.trim(), quantity: String(quantity), currency: selectedCurrency }); const response = await fetch(`/api/quotes/calculate?${query}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error || t("Unable to calculate quote.", "无法计算报价。")); setPreview(result); } catch (e) { setPreview(null); setError(e instanceof Error ? e.message : t("Unable to calculate quote.", "无法计算报价。")); } finally { setLoading(false); } }
  useEffect(() => { if (productId) void calculate(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!preview) return; setLoading(true); setError(""); const data = new FormData(event.currentTarget); try { const response = await fetch("/api/quotes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(data.entries()), productId: preview.product.id, quantity: preview.quantity, currency: preview.currency, locale: lang, consentPrivacy: data.get("consentPrivacy") === "on", consentMarketing: data.get("consentMarketing") === "on" }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || t("Unable to create quote.", "无法创建报价。")); setSaved(result); } catch (e) { setError(e instanceof Error ? e.message : t("Unable to create quote.", "无法创建报价。")); } finally { setLoading(false); } }

  const input = "w-full rounded-xl border border-secondary-200 bg-white px-4 py-3 text-sm text-secondary-700 outline-none transition focus:border-primary-400 focus:ring-4 focus:ring-primary-100/60";
  const money = (value: number) => new Intl.NumberFormat(zh ? "zh-CN" : "en-US", { style: "currency", currency: selectedCurrency }).format(value);
  return <div className="grid gap-8 lg:grid-cols-[1.05fr_.95fr]">
    <section className="rounded-2xl border border-secondary-100 bg-white p-6 shadow-sm md:p-8"><div className="mb-6 flex items-center gap-3"><div className="rounded-xl bg-primary-50 p-3"><Calculator className="h-5 w-5 text-primary-600" /></div><div><h2 className="font-display text-xl font-bold text-secondary-900">{t("Configure your quote", "配置报价")}</h2><p className="text-sm text-secondary-400">{t("Enter a catalog ID and quantity.", "输入产品货号和数量。")}</p></div></div>
      <div className="grid gap-4 sm:grid-cols-[1fr_120px_130px]"><label className="text-xs font-semibold uppercase tracking-wide text-secondary-500">{t("Catalog ID", "产品货号")}<input value={productId} onChange={event => setProductId(event.target.value)} className={`${input} mt-2 font-mono`} placeholder="CBP60004" /></label><label className="text-xs font-semibold uppercase tracking-wide text-secondary-500">{t("Quantity", "数量")}<input value={quantity} onChange={event => setQuantity(Math.max(1, Number(event.target.value) || 1))} type="number" min="1" max="100000" className={`${input} mt-2`} /></label><label className="text-xs font-semibold uppercase tracking-wide text-secondary-500">{t("Currency", "币种")}<select value={selectedCurrency} onChange={event => setSelectedCurrency(event.target.value as "USD" | "EUR" | "CNY")} className={`${input} mt-2`}><option>USD</option><option>EUR</option><option>CNY</option></select></label></div>
      <button onClick={calculate} disabled={loading || !productId.trim()} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary-600 px-5 py-3 text-sm font-semibold text-white hover:bg-primary-700 disabled:opacity-50">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Calculator className="h-4 w-4" />}{t("Calculate", "计算")}</button>
      {error && <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error} {error.toLowerCase().includes("manual") && <a href={`/contact?product=${encodeURIComponent(productId)}`} className="font-semibold underline">{t("Request manually", "申请人工报价")}</a>}</div>}
      {preview && <div className="mt-6 rounded-2xl border border-primary-100 bg-primary-50/50 p-5"><div className="flex justify-between gap-4"><div><p className="font-mono text-xs font-semibold text-primary-600">{preview.product.id}</p><h3 className="mt-1 font-semibold text-secondary-900">{preview.product.name}</h3></div><span className="h-fit rounded-full bg-white px-3 py-1 text-xs font-medium text-secondary-500">{t("Valid to", "有效期至")} {preview.validUntil}</span></div><dl className="mt-5 space-y-2 border-t border-primary-100 pt-4 text-sm"><div className="flex justify-between"><dt>{t("Unit price", "单价")}</dt><dd>{money(preview.unitPrice)}</dd></div><div className="flex justify-between"><dt>{t("Quantity", "数量")}</dt><dd>{preview.quantity}</dd></div><div className="flex justify-between"><dt>{t("Subtotal", "小计")}</dt><dd>{money(preview.subtotal)}</dd></div>{preview.discountAmount > 0 && <div className="flex justify-between text-emerald-700"><dt>{t("Volume discount", "数量折扣")} ({preview.discountRate * 100}%)</dt><dd>-{money(preview.discountAmount)}</dd></div>}<div className="flex justify-between border-t border-primary-100 pt-3 text-lg font-bold text-primary-800"><dt>{t("Estimated total", "预计合计")}</dt><dd>{money(preview.total)}</dd></div></dl><p className="mt-4 text-[11px] leading-relaxed text-secondary-400">{t("Indicative product price only. Freight, import duties, local taxes and special handling are excluded. Final availability is subject to confirmation.", "仅为产品参考价，不含运费、进口关税、当地税费和特殊处理费，最终库存需销售确认。")}</p></div>}
    </section>
    <section className="rounded-2xl border border-secondary-100 bg-white p-6 shadow-sm md:p-8"><div className="mb-6 flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-primary-600" /><div><h2 className="font-display text-xl font-bold text-secondary-900">{t("Generate formal PDF", "生成正式PDF")}</h2><p className="text-sm text-secondary-400">{t("Save your quote and download a shareable PDF.", "保存报价并下载可分享的PDF。")}</p></div></div>
      {!preview ? <div className="rounded-xl border border-dashed border-secondary-200 p-10 text-center text-sm text-secondary-400">{t("Calculate a product price first.", "请先计算产品价格。")}</div> : saved ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600" /><h3 className="mt-3 font-bold text-emerald-900">{t("Quote", "报价单")} {saved.quoteNumber} {t("created", "已创建")}</h3><p className="mt-2 text-sm text-emerald-700">{saved.currency} {saved.total.toFixed(2)} · {t("valid until", "有效期至")} {saved.validUntil}</p><a href={saved.pdfUrl} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white"><Download className="h-4 w-4" />{t("Download PDF quote", "下载PDF报价单")}</a></div> : <form onSubmit={save} className="space-y-4"><input name="website" className="hidden" tabIndex={-1} /><input required name="fullName" className={input} placeholder={t("Full name *", "姓名 *")} autoComplete="name" /><input required type="email" name="email" className={input} placeholder={t("Business email *", "商务邮箱 *")} autoComplete="email" /><input name="company" className={input} placeholder={t("Company / institution", "公司／机构")} autoComplete="organization" /><input name="country" className={input} placeholder={t("Country / region", "国家／地区")} autoComplete="country-name" /><textarea name="notes" rows={3} className={`${input} resize-y`} placeholder={t("Delivery destination or special requirements", "交付目的地或特殊要求")} /><label className="flex items-start gap-3 text-xs leading-relaxed text-secondary-500"><input required name="consentPrivacy" type="checkbox" className="mt-0.5" /><span>{t("I agree to the", "我同意")} <a href="/privacy" className="font-semibold text-primary-600">{t("Privacy Policy", "隐私政策")}</a> {t("and processing required to create this quote.", "以及为生成本报价所需的数据处理。")} *</span></label><label className="flex items-start gap-3 text-xs leading-relaxed text-secondary-500"><input name="consentMarketing" type="checkbox" className="mt-0.5" /><span>{t("Send me relevant product updates. Optional.", "向我发送相关产品更新（可选）。")}</span></label><button disabled={loading} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-secondary-900 px-5 py-3.5 text-sm font-semibold text-white hover:bg-secondary-800 disabled:opacity-50">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}{t("Create & save PDF quote", "创建并保存PDF报价")}</button></form>}
    </section>
  </div>;
}
