"use client";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Calculator, CheckCircle2, Download, Loader2, Mail, ShieldCheck } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { salesMailto } from "@/lib/sales-mailto";

type Preview = { product: { id: string; name: string }; quantity: number; currency: string; unitPrice: number; subtotal: number; discountRate: number; discountAmount: number; total: number; validUntil: string; exchangeRateSource: "configured" | "ECB" | "base"; exchangeRateDate: string };
type Saved = { quoteNumber: string; total: number; currency: string; validUntil: string; pdfUrl: string };

export default function QuoteBuilder() {
  const params = useSearchParams(); const { lang, currency, t } = useI18n();
  const [productId, setProductId] = useState(params.get("product") || ""); const [quantity, setQuantity] = useState(1); const [selectedCurrency, setSelectedCurrency] = useState(currency);
  const [preview, setPreview] = useState<Preview | null>(null); const [saved, setSaved] = useState<Saved | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [fallbackHref, setFallbackHref] = useState("");
  useEffect(() => setSelectedCurrency(currency), [currency]);

  async function calculate() { if (!productId.trim()) return; setLoading(true); setError(""); setFallbackHref(""); setSaved(null); try { const query = new URLSearchParams({ product: productId.trim(), quantity: String(quantity), currency: selectedCurrency }); const response = await fetch(`/api/quotes/calculate?${query}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error || t("quote.unableCalculate")); setPreview(result); } catch (e) { setPreview(null); setError(e instanceof Error ? e.message : t("quote.unableCalculate")); } finally { setLoading(false); } }
  useEffect(() => { if (productId) void calculate(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!preview) return; setLoading(true); setError(""); setFallbackHref(""); const data = new FormData(event.currentTarget); const fallback = salesMailto(`Formal quote request - ${preview.product.id}`, [["Name", data.get("fullName")], ["Business email", data.get("email")], ["Company", data.get("company")], ["Country", data.get("country")], ["Product", `${preview.product.id} - ${preview.product.name}`], ["Quantity", preview.quantity], ["Currency", preview.currency], ["Indicative total", preview.total], ["Valid until", preview.validUntil], ["Requirements", data.get("notes")]]); try { const response = await fetch("/api/quotes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(data.entries()), productId: preview.product.id, quantity: preview.quantity, currency: preview.currency, locale: lang, consentPrivacy: data.get("consentPrivacy") === "on", consentMarketing: data.get("consentMarketing") === "on" }) }); const result = await response.json(); if (!response.ok) throw new Error(response.status >= 500 ? t("quote.serviceUnavailable") : result.error || t("quote.unableCreate")); setSaved(result); } catch (e) { setError(e instanceof Error ? e.message : t("quote.unableCreate")); setFallbackHref(fallback); } finally { setLoading(false); } }

  const input = "w-full rounded-xl border border-secondary-200 bg-white px-4 py-3 text-sm text-secondary-700 outline-none transition focus:border-primary-400 focus:ring-4 focus:ring-primary-100/60";
  const money = (value: number) => new Intl.NumberFormat(lang === "zh" ? "zh-CN" : lang, { style: "currency", currency: selectedCurrency }).format(value);
  return <div className="grid gap-8 lg:grid-cols-[1.05fr_.95fr]">
    <section className="rounded-2xl border border-secondary-100 bg-white p-6 shadow-sm md:p-8"><div className="mb-6 flex items-center gap-3"><div className="rounded-xl bg-primary-50 p-3"><Calculator className="h-5 w-5 text-primary-600" /></div><div><h2 className="font-display text-xl font-bold text-secondary-900">{t("quote.configure")}</h2><p className="text-sm text-secondary-400">{t("quote.configureDesc")}</p></div></div>
      <div className="grid gap-4 sm:grid-cols-[1fr_120px_130px]"><label className="text-xs font-semibold uppercase tracking-wide text-secondary-500">{t("quote.catalogId")}<input value={productId} onChange={event => setProductId(event.target.value)} className={`${input} mt-2 font-mono`} placeholder="CBP60004" /></label><label className="text-xs font-semibold uppercase tracking-wide text-secondary-500">{t("quote.quantity")}<input value={quantity} onChange={event => setQuantity(Math.max(1, Number(event.target.value) || 1))} type="number" min="1" max="100000" className={`${input} mt-2`} /></label><label className="text-xs font-semibold uppercase tracking-wide text-secondary-500">{t("quote.currency")}<select value={selectedCurrency} onChange={event => setSelectedCurrency(event.target.value as "USD" | "EUR" | "CNY")} className={`${input} mt-2`}><option>USD</option><option>EUR</option><option>CNY</option></select></label></div>
      <button onClick={calculate} disabled={loading || !productId.trim()} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary-600 px-5 py-3 text-sm font-semibold text-white hover:bg-primary-700 disabled:opacity-50">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Calculator className="h-4 w-4" />}{t("quote.calculate")}</button>
      {error && <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><div>{error} {error.toLowerCase().includes("manual") && <a href={`/contact?product=${encodeURIComponent(productId)}`} className="font-semibold underline">{t("quote.requestManually")}</a>}</div>{fallbackHref && <a href={fallbackHref} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-red-700 px-4 py-2 text-xs font-semibold text-white hover:bg-red-800"><Mail className="h-3.5 w-3.5" />{t("quote.emailSales")}</a>}</div>}
      {preview && <div className="mt-6 rounded-2xl border border-primary-100 bg-primary-50/50 p-5"><div className="flex justify-between gap-4"><div><p className="font-mono text-xs font-semibold text-primary-600">{preview.product.id}</p><h3 className="mt-1 font-semibold text-secondary-900">{preview.product.name}</h3></div><span className="h-fit rounded-full bg-white px-3 py-1 text-xs font-medium text-secondary-500">{t("quote.validTo")} {preview.validUntil}</span></div><dl className="mt-5 space-y-2 border-t border-primary-100 pt-4 text-sm"><div className="flex justify-between"><dt>{t("quote.unitPrice")}</dt><dd>{money(preview.unitPrice)}</dd></div><div className="flex justify-between"><dt>{t("quote.quantity")}</dt><dd>{preview.quantity}</dd></div><div className="flex justify-between"><dt>{t("quote.subtotal")}</dt><dd>{money(preview.subtotal)}</dd></div>{preview.discountAmount > 0 && <div className="flex justify-between text-emerald-700"><dt>{t("quote.volumeDiscount")} ({preview.discountRate * 100}%)</dt><dd>-{money(preview.discountAmount)}</dd></div>}<div className="flex justify-between border-t border-primary-100 pt-3 text-lg font-bold text-primary-800"><dt>{t("quote.estimatedTotal")}</dt><dd>{money(preview.total)}</dd></div></dl>{preview.exchangeRateSource === "ECB" && <p className="mt-3 text-[10px] text-secondary-400">{t("quote.fxReference", { date: preview.exchangeRateDate })}</p>}<p className="mt-2 text-[11px] leading-relaxed text-secondary-400">{t("quote.disclaimer")}</p></div>}
    </section>
    <section className="rounded-2xl border border-secondary-100 bg-white p-6 shadow-sm md:p-8"><div className="mb-6 flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-primary-600" /><div><h2 className="font-display text-xl font-bold text-secondary-900">{t("quote.generatePdf")}</h2><p className="text-sm text-secondary-400">{t("quote.pdfDesc")}</p></div></div>
      {!preview ? <div className="rounded-xl border border-dashed border-secondary-200 p-10 text-center text-sm text-secondary-400">{t("quote.calculateFirst")}</div> : saved ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600" /><h3 className="mt-3 font-bold text-emerald-900">{t("quote.quote")} {saved.quoteNumber} {t("quote.created")}</h3><p className="mt-2 text-sm text-emerald-700">{saved.currency} {saved.total.toFixed(2)} · {t("quote.validUntil")} {saved.validUntil}</p><a href={saved.pdfUrl} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white"><Download className="h-4 w-4" />{t("quote.downloadPdf")}</a></div> : <form onSubmit={save} className="space-y-4"><input name="website" className="hidden" tabIndex={-1} /><input required name="fullName" className={input} placeholder={`${t("inquiry.fullName")} *`} autoComplete="name" /><input required type="email" name="email" className={input} placeholder={`${t("inquiry.businessEmail")} *`} autoComplete="email" /><input name="company" className={input} placeholder={t("inquiry.company")} autoComplete="organization" /><input name="country" className={input} placeholder={t("inquiry.country")} autoComplete="country-name" /><textarea name="notes" rows={3} className={`${input} resize-y`} placeholder={t("quote.notes")} /><label className="flex items-start gap-3 text-xs leading-relaxed text-secondary-500"><input required name="consentPrivacy" type="checkbox" className="mt-0.5" /><span>{t("inquiry.agreeTo")} <a href="/privacy" className="font-semibold text-primary-600">{t("inquiry.privacyPolicy")}</a> {t("quote.consent")} *</span></label><label className="flex items-start gap-3 text-xs leading-relaxed text-secondary-500"><input name="consentMarketing" type="checkbox" className="mt-0.5" /><span>{t("quote.marketing")}</span></label><button disabled={loading} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-secondary-900 px-5 py-3.5 text-sm font-semibold text-white hover:bg-secondary-800 disabled:opacity-50">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}{t("quote.createSave")}</button></form>}
    </section>
  </div>;
}
