"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, FileText, KeyRound, Loader2, RefreshCw } from "lucide-react";

type Lead = { full_name: string; email: string; company?: string; country?: string };
type Item = { product_id: string; product_name: string; quantity: number; unit_price: number; line_total: number };
type Quote = { id: string; quote_number: string; currency: string; subtotal: number; discount_amount: number; total: number; status: string; valid_until: string; created_at: string; leads: Lead | Lead[]; quote_items: Item[] };

export default function QuoteHistory() {
  const [key, setKey] = useState(""); const [draft, setDraft] = useState(""); const [items, setItems] = useState<Quote[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  useEffect(() => setKey(sessionStorage.getItem("cobioer_admin_key") || ""), []);
  async function load(active = key) { if (!active) return; setLoading(true); setError(""); try { const response = await fetch("/api/admin/quotes", { headers: { Authorization: `Bearer ${active}` }, cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setItems(result.data || []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load quotes."); } finally { setLoading(false); } }
  useEffect(() => { if (key) void load(key); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [key]);
  if (!key) return <div className="mx-auto max-w-md rounded-2xl border border-secondary-200 bg-white p-8 shadow-sm"><KeyRound className="mb-4 h-8 w-8 text-primary-600" /><h1 className="text-2xl font-bold">Quote history</h1><p className="mt-2 text-sm text-secondary-500">Use the same access key as the sales workspace.</p><input type="password" value={draft} onChange={e => setDraft(e.target.value)} className="mt-5 w-full rounded-xl border border-secondary-200 px-4 py-3" /><button onClick={() => { const value = draft.trim(); if (value) { sessionStorage.setItem("cobioer_admin_key", value); setKey(value); } }} className="mt-3 w-full rounded-xl bg-primary-600 py-3 text-sm font-semibold text-white">Open history</button></div>;
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><Link href="/admin" className="inline-flex items-center gap-1 text-xs font-semibold text-primary-600"><ArrowLeft className="h-3 w-3" />Inquiries</Link><h1 className="mt-2 text-3xl font-bold text-secondary-900">Quote history</h1></div><button onClick={() => load()} className="rounded-xl border border-secondary-200 bg-white p-3">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}</button></div>{error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="space-y-3">{items.map(q => { const lead = Array.isArray(q.leads) ? q.leads[0] : q.leads; return <article key={q.id} className="rounded-2xl border border-secondary-100 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-primary-600" /><span className="font-mono text-xs font-bold text-primary-700">{q.quote_number}</span><span className="rounded-full bg-secondary-50 px-2 py-1 text-[10px] uppercase text-secondary-500">{q.status}</span></div><h2 className="mt-3 font-semibold text-secondary-900">{lead?.company || lead?.full_name}</h2><a href={`mailto:${lead?.email}`} className="text-xs text-primary-600">{lead?.email}</a><div className="mt-3 space-y-1">{q.quote_items?.map(item => <p key={item.product_id} className="text-xs text-secondary-500">{item.product_id} · {item.product_name} × {item.quantity}</p>)}</div></div><div className="text-left md:text-right"><p className="text-xs text-secondary-400">Created {new Date(q.created_at).toLocaleDateString()}</p><p className="mt-2 text-2xl font-bold text-secondary-900">{q.currency} {Number(q.total).toFixed(2)}</p><p className="text-xs text-secondary-400">Valid until {q.valid_until}</p></div></div></article>; })}{!loading && !error && items.length === 0 && <div className="rounded-2xl border border-dashed border-secondary-200 p-16 text-center text-sm text-secondary-400">No saved quotes.</div>}</div></div>;
}

