"use client";
import { CheckCircle2 } from "lucide-react";
import { useI18n } from "@/lib/i18n";
const reasons = [
  ["Documented quality", "文件化质量", "Identity, contamination and performance controls matched to product type.", "根据产品类型匹配身份、污染和性能控制。"],
  ["Commercial responsiveness", "商务响应", "Structured inquiries, transparent lead times and regional routing.", "结构化询盘、透明交期和区域分配。"],
  ["Deep product coverage", "广泛产品覆盖", "More than 7,000 catalog products across research and diagnostics.", "覆盖科研和诊断领域的 7,000+ 目录产品。"],
  ["Technical partnership", "技术伙伴", "Application-focused support from selection through experimental use.", "从产品选择到实验应用的场景化技术支持。"],
];
export default function WhyUs() { const { lang } = useI18n(); const en = lang !== "zh"; return <section className="section-padding bg-neutral-50"><div className="container-page"><div className="mb-12 text-center"><h2 className="heading-2 mb-4">{en ? "Why global teams choose Cobioer" : "全球团队为何选择科佰"}</h2><p className="body-text mx-auto max-w-2xl">{en ? "A practical combination of product breadth, quality discipline and responsive scientific support." : "兼具产品广度、质量纪律和快速科学支持。"}</p></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{reasons.map(reason => <div key={reason[0]} className="rounded-xl border border-neutral-100 bg-white p-6"><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-50"><CheckCircle2 className="h-5 w-5 text-emerald-600" /></div><h3 className="text-lg font-semibold text-neutral-800">{en ? reason[0] : reason[1]}</h3><p className="mt-2 text-sm leading-relaxed text-neutral-500">{en ? reason[2] : reason[3]}</p></div>)}</div><div className="mt-12 flex flex-wrap justify-center gap-3">{["ISO 13485-oriented", "ISO 9001-oriented", "Batch traceability", "Global commercial support"].map(item => <span key={item} className="inline-flex items-center gap-2 rounded-lg border border-neutral-100 bg-white px-4 py-2.5 text-xs font-medium text-neutral-600"><CheckCircle2 className="h-4 w-4 text-emerald-500" />{item}</span>)}</div></div></section>; }
